name: flutter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.4.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  riverpod_annotation: ^2.3.0
  state_notifier: ^0.7.2+1
  go_router: ^12.0.1
  sqflite: ^2.3.0
  path: ^1.8.3
  webview_flutter: ^4.4.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.3
  mocktail: ^0.3.0
  riverpod_generator: ^2.3.5
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0

flutter:
  uses-material-design: true
